name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # или node-version-file: '.nvmrc'
          node-version: '20'
          cache: 'npm'

      - name: Debug info
        run: |
          node -v
          npm -v
          jq -r '.scripts' package.json || true

      - name: Install
        run: npm ci --no-audit --no-fund

      # Ако е CRA, CI=false за да не падне на warning
      - name: Build
        env:
          CI: false  # махни ако не е CRA
          # Примери за env, ако трябват:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: |
            dist
            build
            out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: needs.build.result == 'success'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: web-build
          path: builddir

      # TODO: сложи реалния си деплой (GitHub Pages, FTP, rsync, Vercel CLI и т.н.)
      - name: Deploy (placeholder)
        run: echo "Deploy from ./builddir"
